language: rust
cache: cargo
sudo: false
dist: xenial

os:
- linux
- osx
- windows

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - zlib1g-dev

# run builds for all the trains
rust:
- 1.31.1
- stable
- beta
- nightly

# Extra jobs to include
jobs:
  include:
  # Upload documentation
  - name: "Documentation upload"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      github-token: $GH_TOKEN
      local-dir: target/doc/
      skip_cleanup: true
      keep-history: true
      on:
        repo: Razican/Space-Settler-BigBang
        branch: develop

matrix:
  allow_failures:
  - os: windows
  - rust: nightly

# Run the multiple tests.
script:
- ./travis-helper.sh fmt_check
- ./travis-helper.sh clippy_check
- ./travis-helper.sh test
