language: rust
sudo: false
dist: trusty
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

# run builds for all the trains
rust:
  - nightly
  - beta
  - stable
  - 1.11.0
  - 1.4.0

# load travis-cargo
before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install git+https://github.com/FractalGlobal/travis-cargo.git@fix-coveralls --user &&
      export PATH=$HOME/.local/bin:$PATH
      fi

# the main build
script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc;
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cargo build -v &&
      cargo test &&
      cargo bench;
      fi
after_success:
  - |
      if [["$TRAVIS_OS_NAME" == "linux"]]; then
      travis-cargo --only stable doc-upload;
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis-cargo --only stable coveralls --no-sudo --verify;
      fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
