[package]
name = "bigbang"
version = "0.0.2"
authors = ["Razican <razican@protonmail.ch>"]
license = "BSD 3-Clause License"
readme = "README.md"
repository = "https://github.com/Razican/Space-Settler-BigBang"
description = """
Big-Bang generator for Space Settler.
"""

[dependencies]
rand="0.4.2" # In the future substitute by Mersenne Twister

# The release profile, used for `cargo build`.
[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
panic = 'unwind'

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'unwind'
