table! {
    use diesel::sql_types::*;

    /// Representation of the `planets` table.
    ///
    /// (Automatically generated by Diesel.)
    planets (id) {
        /// The `id` column of the `planets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `star_id` column of the `planets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        star_id -> Int4,
        /// The `position` column of the `planets` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        position -> Int2,
        /// The `orb_ecc` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        orb_ecc -> Float8,
        /// The `orb_sma` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        orb_sma -> Float8,
        /// The `orb_incl` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        orb_incl -> Float8,
        /// The `orb_lan` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        orb_lan -> Float8,
        /// The `orb_arg_p` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        orb_arg_p -> Float8,
        /// The `orb_m0` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        orb_m0 -> Float8,
        /// The `orb_period` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        orb_period -> Float8,
        /// The `atm_pressure` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_pressure -> Nullable<Float8>,
        /// The `atm_h2o` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_h2o -> Nullable<Float8>,
        /// The `atm_co2` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_co2 -> Nullable<Float8>,
        /// The `atm_co` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_co -> Nullable<Float8>,
        /// The `atm_n2` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_n2 -> Nullable<Float8>,
        /// The `atm_o2` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_o2 -> Nullable<Float8>,
        /// The `atm_ar` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_ar -> Nullable<Float8>,
        /// The `atm_so2` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_so2 -> Nullable<Float8>,
        /// The `atm_ne` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_ne -> Nullable<Float8>,
        /// The `atm_ch4` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_ch4 -> Nullable<Float8>,
        /// The `atm_he` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        atm_he -> Nullable<Float8>,
        /// The `ax_tilt` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        ax_tilt -> Float8,
        /// The `rot_period` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        rot_period -> Float8,
        /// The `planet_type` column of the `planets` table.
        ///
        /// Its SQL type is `crate::planets::PlanetTypeMapping`.
        ///
        /// (Automatically generated by Diesel.)
        planet_type -> crate::planets::PlanetTypeMapping,
        /// The `surf_fresh_water` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        surf_fresh_water -> Nullable<Float8>,
        /// The `surf_ocean_water` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        surf_ocean_water -> Nullable<Float8>,
        /// The `surf_snow` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        surf_snow -> Nullable<Float8>,
        /// The `surf_land` column of the `planets` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        surf_land -> Nullable<Float8>,
        /// The `bond_albedo` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        bond_albedo -> Float8,
        /// The `geometric_albedo` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        geometric_albedo -> Float8,
        /// The `mass` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        mass -> Float8,
        /// The `radius` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        radius -> Float8,
        /// The `eff_temp` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        eff_temp -> Float8,
        /// The `min_temp` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        min_temp -> Float8,
        /// The `max_temp` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        max_temp -> Float8,
        /// The `avg_temp` column of the `planets` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        avg_temp -> Float8,
        /// The `habitable` column of the `planets` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        habitable -> Bool,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `stars` table.
    ///
    /// (Automatically generated by Diesel.)
    stars (id) {
        /// The `id` column of the `stars` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `orb_radius` column of the `stars` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        orb_radius -> Int4,
        /// The `class` column of the `stars` table.
        ///
        /// Its SQL type is `crate::stars::StarClassMapping`.
        ///
        /// (Automatically generated by Diesel.)
        class -> crate::stars::StarClassMapping,
        /// The `mass` column of the `stars` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        mass -> Float8,
        /// The `radius` column of the `stars` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        radius -> Float8,
        /// The `temperature` column of the `stars` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        temperature -> Nullable<Int4>,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Nullable<Varchar>,
        /// The `password` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bpchar>`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Nullable<Bpchar>,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Nullable<Varchar>,
        /// The `reg_time` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        reg_time -> Nullable<Timestamptz>,
        /// The `last_online` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_online -> Nullable<Timestamptz>,
    }
}

joinable!(planets -> stars (star_id));

allow_tables_to_appear_in_same_query!(planets, stars, users,);
